export const GET_SPECIFIC_CRYPTO = "GET_SPECIFIC_CRYPTO";
export const GET_ALL_CRYPTOS = "GET_ALL_CRYPTOS";
export const SET_ERROR = "SET_ERROR";
export const SET_LOADING = "SET_LOADING";
export const EXPLORE_BLOCKCHAIN = "EXPLORE_BLOCKCHAIN";
export const TOGGLE_SIDEBAR_MENU = "TOGGLE_SIDEBAR_MENU";
